# See https://houndci.com/configuration for help.
fail_on_violations: true
javascript:
  # config_file: .javascript-style.json
  enabled: true
  # ignore_file: .javascript_ignore
ruby:
  config_file: .rubocop.yml
  enabled: true
scss:
  # config_file: .scss-style.yml
  enabled: true
